# Generated by Django 4.1.7 on 2023-06-10 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_user_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_post',
        ),
    ]
