# Generated by Django 4.1.7 on 2023-06-10 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_delete_user_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_followers',
        ),
        migrations.AddField(
            model_name='user',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_users', to='network.post'),
        ),
    ]
